/**
 * Maps a validated proposal input to the exact rows persisted for it.
 *
 * PURE — no Prisma, no session, no server-only imports — so the data layer stays the only
 * thing that talks to the database while this engine→row wiring is independently unit-tested.
 * Every monetary figure written to the header and to child rows comes from `computeProposal`;
 * the client cannot supply a total.
 */
import { computeProposal } from "./engine/engine";
import type { ProposalCalcInput } from "./engine/types";
import type { ServiceProposalInput } from "./schema/proposal";

/** Normalise a date string to a Date, or null. The schema permits "" (empty) for an unset
 *  date, which Prisma would reject as an invalid DateTime — so it must become null here. */
function toDate(s: string | null | undefined): Date | null {
  if (!s) return null;
  const d = new Date(s);
  return Number.isNaN(d.getTime()) ? null : d;
}

export function buildWriteData(input: ServiceProposalInput) {
  const calc = computeProposal(input as ProposalCalcInput);

  const componentAmount = new Map(calc.components.map((c) => [c.id, c.calculatedAmount]));
  const phaseAmount = new Map(calc.phases.map((p) => [p.id, p.amount]));
  const milestoneAmount = new Map(calc.paymentSchedule.map((m) => [m.id, m.amount]));

  const header = {
    title: input.title.trim(),
    kind: input.kind,
    clientId: input.clientId ?? null,
    clientName: input.clientName ?? null,
    projectId: input.projectId ?? null,
    projectName: input.projectName ?? null,
    contactName: input.contactName ?? null,
    contactEmail: input.contactEmail || null,
    contactTitle: input.contactTitle ?? null,
    currency: input.currency,
    languageCode: input.languageCode ?? null,
    taxJurisdiction: input.taxJurisdiction ?? null,
    costBasisType: input.costBasis?.type ?? null,
    costBasisAmount: input.costBasis ? (calc.basis?.amount ?? null) : null,
    costBasisSourceId: input.costBasis?.sourceId ?? null,
    costBasisSourceField: input.costBasis?.sourceField ?? null,
    costBasisCapturedAt: input.costBasis ? new Date() : null,
    subtotal: calc.totals.subtotal,
    discountTotal: calc.totals.discountTotal,
    taxableSubtotal: calc.totals.taxableSubtotal,
    taxTotal: calc.totals.taxTotal,
    grandTotal: calc.totals.grandTotal,
    baseFeeTotal: calc.totals.baseFeeTotal,
    optionalServicesTotal: calc.totals.optionalServicesTotal,
    reimbursablesTotal: calc.totals.reimbursablesTotal,
    scopeSummary: input.scopeSummary ?? null,
    exclusions: input.exclusions ?? null,
    assumptions: input.assumptions ?? null,
    terms: input.terms ?? null,
    estimatedWeeks: input.estimatedWeeks ?? null,
    showFeeDerivation: input.showFeeDerivation,
    validUntil: toDate(input.validUntil),
    notes: input.notes ?? null,
  };

  // Child create payloads. New cuids are generated by Prisma; the client-side ids are used
  // only to line engine results back up to their inputs above.
  const feeComponents = input.feeComponents.map((c, i) => ({
    label: c.label,
    disciplineKey: c.disciplineKey ?? null,
    method: c.method,
    category: c.category,
    percent: c.percent ?? null,
    fixedAmount: c.fixedAmount ?? null,
    quantity: c.quantity ?? null,
    unitRate: c.unitRate ?? null,
    baseAmount: c.baseAmount ?? null,
    markupPercent: c.markupPercent ?? null,
    selected: c.selected ?? false,
    taxable: c.taxable !== false,
    calculatedAmount: componentAmount.get(c.id) ?? 0,
    overrideAmount: c.overrideAmount ?? null,
    overrideReason: c.overrideReason ?? null,
    sortOrder: i,
  }));

  const phases = input.phases.map((p, i) => ({
    name: p.name,
    percent: p.percent,
    amount: phaseAmount.get(p.id) ?? 0,
    sortOrder: i,
  }));

  const paymentMilestones = input.paymentMilestones.map((m, i) => ({
    name: m.name,
    trigger: m.trigger ?? null,
    percent: m.percent,
    amount: milestoneAmount.get(m.id) ?? 0,
    taxable: true,
    sortOrder: i,
  }));

  const reimbursables = input.reimbursables.map((r, i) => ({
    label: r.label,
    amount: r.amount,
    taxable: r.taxable !== false,
    sortOrder: i,
  }));

  const discounts = input.discounts.map((d, i) => ({
    label: d.label,
    type: d.type,
    value: d.value,
    reason: d.reason ?? null,
    visibleToClient: d.visibleToClient !== false,
    sortOrder: i,
  }));

  const taxes = input.taxes.map((t, i) => ({
    name: t.name,
    percent: t.percent,
    mode: t.mode,
    registrationNumber: t.registrationNumber ?? null,
    sortOrder: i,
  }));

  const developmentCostItems = (input.costBasis?.worksheet ?? []).map((d, i) => ({
    category: d.category,
    amount: d.amount,
    includedInBasis: d.includedInBasis,
    isProfessionalFees: d.isProfessionalFees ?? false,
    notes: d.notes ?? null,
    sortOrder: i,
  }));

  return {
    calc,
    header,
    children: {
      feeComponents,
      phases,
      paymentMilestones,
      reimbursables,
      discounts,
      taxes,
      developmentCostItems,
    },
  };
}

/** Next number in the SP-{year}-{NNN} series, sequential within a company. Reads ALL numbers
 *  (including soft-deleted) so a number is never reused. Pure. */
export function nextProposalNumber(existing: string[], year: number): string {
  let max = 0;
  for (const n of existing) {
    const m = /(\d+)\s*$/.exec(n);
    if (m && Number(m[1]) > max) max = Number(m[1]);
  }
  return `SP-${year}-${String(max + 1).padStart(3, "0")}`;
}
