// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from here (no longer package.json#prisma.seed).
    seed:
      'ts-node --compiler-options {"module":"commonjs","moduleResolution":"node"} -r tsconfig-paths/register prisma/seed.ts',
  },
  datasource: {
    // Migrate/Studio use the direct connection (no pgbouncer pooling params).
    // The app runtime (lib/db.ts) uses the pooled DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
