/**
 * Construction Administration — sample data.
 *
 * Single source of demo data, used two ways:
 *   1. As the offline fallback in the repositories (lib/data/ca/*) so the UI
 *      renders while the Supabase database is paused/unreachable.
 *   2. As the input to `prisma db seed` (prisma/seed.ts) once the DB is live.
 *
 * Derived money fields (change-order total, revised contract value, progress
 * payment) are computed here with lib/ca/calc.ts so the seed always agrees with
 * the live calculation.
 */
import { changeOrderTotal, revisedContractValue, progressPayment } from "@/lib/ca/calc";
import type {
  ChangeOrder,
  Rfi,
  CaReport,
  ProgressCertification,
  PunchListItem,
  SiteInstruction,
  Submittal,
  DelayNotice,
  ChangeOrderCosts,
} from "@/lib/ca/types";

type CoSeed = Omit<ChangeOrder, "totalCost" | "revisedContractValue"> & ChangeOrderCosts;

function co(seed: CoSeed): ChangeOrder {
  const totalCost = changeOrderTotal(seed);
  return {
    ...seed,
    totalCost,
    revisedContractValue: revisedContractValue(
      seed.originalContractValue,
      seed.approvedChangeOrdersToDate + (seed.status === "APPROVED" ? totalCost : 0),
    ),
  };
}

export const SEED_CHANGE_ORDERS: ChangeOrder[] = [
  co({
    id: "co_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    changeOrderNumber: "CO-2026-014-007",
    version: 1,
    title: "Upgrade lobby flooring to large-format porcelain",
    description: "Replace 600×600 tiles with 1200×2400 porcelain to lobby and lift cores.",
    reason: "Owner-requested finish upgrade.",
    requestedBy: "Layla Hassan",
    contractor: "Tameer Construction",
    architect: "ZenArch Consultants",
    engineer: "ZenArch Structural",
    owner: "Aldar Properties",
    status: "APPROVED",
    currency: "AED",
    costLabor: 28800,
    costMaterial: 76800,
    costEquipment: 4200,
    costSubcontractor: 0,
    overheadPercentage: 8,
    profitPercentage: 6,
    contingencyPercentage: 3,
    vatPercentage: 5,
    scheduleImpactDays: 6,
    originalContractValue: 2750000,
    approvedChangeOrdersToDate: 41000,
    estimateLineItemId: "li2",
    dateRequested: "2026-06-08",
    dateSubmitted: "2026-06-09",
    dateApproved: "2026-06-11",
    notes: null,
    createdAt: "2026-06-08",
    updatedAt: "2026-06-11",
  }),
  co({
    id: "co_002",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    changeOrderNumber: "CO-2026-014-008",
    version: 1,
    title: "Additional waterproofing — L3 plant room",
    description: "Tanking to plant room floor and walls after revised MEP layout.",
    reason: "Design development / coordination.",
    requestedBy: "Ahmed Nabil",
    contractor: "Tameer Construction",
    architect: "ZenArch Consultants",
    engineer: "ZenArch MEP",
    owner: "Aldar Properties",
    status: "UNDER_REVIEW",
    currency: "AED",
    costLabor: 15400,
    costMaterial: 22300,
    costEquipment: 1800,
    costSubcontractor: 9500,
    overheadPercentage: 8,
    profitPercentage: 6,
    contingencyPercentage: 5,
    vatPercentage: 5,
    scheduleImpactDays: 3,
    originalContractValue: 2750000,
    approvedChangeOrdersToDate: 41000,
    estimateLineItemId: null,
    dateRequested: "2026-06-14",
    dateSubmitted: "2026-06-15",
    dateApproved: null,
    notes: "Awaiting owner sign-off.",
    createdAt: "2026-06-14",
    updatedAt: "2026-06-16",
  }),
  co({
    id: "co_003",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    changeOrderNumber: "CO-2026-009-003",
    version: 2,
    title: "Heritage stone cladding substitution",
    description: "Substitute specified limestone for locally sourced equivalent.",
    reason: "Long-lead import risk.",
    requestedBy: "Omar Farouk",
    contractor: "Trojan General Contracting",
    architect: "ZenArch Consultants",
    engineer: "ZenArch Structural",
    owner: "DCT Abu Dhabi",
    status: "SUBMITTED",
    currency: "AED",
    costLabor: 0,
    costMaterial: -48000,
    costEquipment: 0,
    costSubcontractor: 0,
    overheadPercentage: 8,
    profitPercentage: 6,
    contingencyPercentage: 0,
    vatPercentage: 5,
    scheduleImpactDays: -10,
    originalContractValue: 3200000,
    approvedChangeOrdersToDate: 0,
    estimateLineItemId: null,
    dateRequested: "2026-06-10",
    dateSubmitted: "2026-06-12",
    dateApproved: null,
    notes: "Minderwerk (cost reduction / credit).",
    createdAt: "2026-06-10",
    updatedAt: "2026-06-12",
  }),
  co({
    id: "co_004",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    changeOrderNumber: "CO-2026-022-001",
    version: 1,
    title: "Add external feature lighting to podium",
    description: "Architectural feature lighting to podium perimeter and signage zones.",
    reason: "Owner enhancement.",
    requestedBy: "Layla Hassan",
    contractor: "ASGC",
    architect: "ZenArch Consultants",
    engineer: "ZenArch MEP",
    owner: "Emaar Developments",
    status: "DRAFT",
    currency: "AED",
    costLabor: 9200,
    costMaterial: 31500,
    costEquipment: 2600,
    costSubcontractor: 14000,
    overheadPercentage: 10,
    profitPercentage: 7,
    contingencyPercentage: 4,
    vatPercentage: 5,
    scheduleImpactDays: 0,
    originalContractValue: 1850000,
    approvedChangeOrdersToDate: 0,
    estimateLineItemId: null,
    dateRequested: "2026-06-17",
    dateSubmitted: null,
    dateApproved: null,
    notes: null,
    createdAt: "2026-06-17",
    updatedAt: "2026-06-17",
  }),
];

export const SEED_RFIS: Rfi[] = [
  {
    id: "rfi_001",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    rfiNumber: "RFI-2026-009-061",
    subject: "FCU condensate drain clashes with beam B-204",
    question:
      "Condensate drain falls below soffit of beam B-204. Core the beam, or shift the FCU 600 mm east?",
    submittedBy: "Sara Khan",
    assignedTo: "Structural Lead",
    discipline: "MECHANICAL",
    priority: "HIGH",
    status: "OPEN",
    response: null,
    responseBy: null,
    dateSubmitted: "2026-06-12",
    dateRequired: "2026-06-19",
    dateResponded: null,
    linkedChangeOrderId: null,
    createdAt: "2026-06-12",
    updatedAt: "2026-06-12",
  },
  {
    id: "rfi_002",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    rfiNumber: "RFI-2026-014-040",
    subject: "Curtain wall bracket spacing at L9 setback",
    question: "Confirm bracket spacing where the slab edge steps back at Level 9.",
    submittedBy: "Tameer Construction",
    assignedTo: "ZenArch Structural",
    discipline: "STRUCTURAL",
    priority: "NORMAL",
    status: "ANSWERED",
    response: "Maintain 1500 mm spacing; add intermediate bracket at the setback as per sketch SK-114.",
    responseBy: "Omar Farouk",
    dateSubmitted: "2026-06-09",
    dateRequired: "2026-06-16",
    dateResponded: "2026-06-13",
    linkedChangeOrderId: null,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-13",
  },
  {
    id: "rfi_003",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    rfiNumber: "RFI-2026-014-041",
    subject: "Plant room slab waterproofing spec",
    question: "Which tanking system applies to the revised L3 plant room?",
    submittedBy: "Tameer Construction",
    assignedTo: "ZenArch MEP",
    discipline: "PLUMBING",
    priority: "URGENT",
    status: "CLOSED",
    response: "Apply system per spec 07 13 00; see CO-2026-014-008 for the added scope.",
    responseBy: "Ahmed Nabil",
    dateSubmitted: "2026-06-13",
    dateRequired: "2026-06-15",
    dateResponded: "2026-06-14",
    linkedChangeOrderId: "co_002",
    createdAt: "2026-06-13",
    updatedAt: "2026-06-14",
  },
  {
    id: "rfi_004",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    rfiNumber: "RFI-2026-022-012",
    subject: "Tenant signage power provision",
    question: "Confirm power allowance per tenant signage zone for the podium façade.",
    submittedBy: "ASGC",
    assignedTo: "ZenArch MEP",
    discipline: "ELECTRICAL",
    priority: "NORMAL",
    status: "OPEN",
    response: null,
    responseBy: null,
    dateSubmitted: "2026-06-16",
    dateRequired: "2026-06-23",
    dateResponded: null,
    linkedChangeOrderId: null,
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
  },
];

export const SEED_REPORTS: CaReport[] = [
  {
    id: "rep_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    reportType: "WEEKLY",
    reportNumber: "WR-2026-014-024",
    version: 1,
    reportingPeriodStart: "2026-06-08",
    reportingPeriodEnd: "2026-06-14",
    preparedBy: "Ahmed Nabil",
    reviewedBy: "Omar Farouk",
    approvedBy: null,
    status: "SUBMITTED",
    weatherSummary: "Clear, 38–42°C, high afternoon winds Wed.",
    siteConditions: "Dry, access roads clear.",
    workCompleted:
      "L10–L12 slabs poured; façade install to L9; MEP first-fix L6–L8 ongoing.",
    workPlannedNextPeriod: "L13 slab, façade to L11, riser MEP coordination.",
    manpowerSummary: [
      { trade: "Concrete", count: 42, hours: 10 },
      { trade: "Façade", count: 18, hours: 9 },
      { trade: "MEP", count: 26, hours: 9 },
    ],
    materialDeliveries: "Rebar (38t), façade brackets (1 of 2 lots).",
    safetyIncidents: "One near miss (scaffold plank) — closed, toolbox talk issued.",
    qualityIssues: "Minor honeycombing at C-7 column — patched and signed off.",
    delays: "Façade bracket delivery slipped one week; recovered with overtime.",
    risks: "Bracket lot 2 delivery; mitigation: expedited freight.",
    notes: null,
    createdAt: "2026-06-14",
    updatedAt: "2026-06-14",
  },
  {
    id: "rep_002",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    reportType: "BIWEEKLY",
    reportNumber: "BW-2026-009-011",
    version: 1,
    reportingPeriodStart: "2026-06-01",
    reportingPeriodEnd: "2026-06-14",
    preparedBy: "Sara Khan",
    reviewedBy: "Omar Farouk",
    approvedBy: "Omar Farouk",
    status: "APPROVED",
    weatherSummary: "Hot, dry.",
    siteConditions: "Stable.",
    workCompleted: "Substructure complete; ground-floor columns to gridline G.",
    workPlannedNextPeriod: "Suspended slab formwork; heritage cladding mock-up.",
    manpowerSummary: [
      { trade: "Civil", count: 30, hours: 9 },
      { trade: "Formwork", count: 22, hours: 9 },
    ],
    materialDeliveries: "Formwork system, rebar.",
    safetyIncidents: "Nil.",
    qualityIssues: "Nil.",
    delays: "Cladding sample approval pending (see CO-2026-009-003).",
    risks: "Stone import lead time.",
    notes: null,
    createdAt: "2026-06-14",
    updatedAt: "2026-06-15",
  },
  {
    id: "rep_003",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    reportType: "MONTHLY",
    reportNumber: "MR-2026-014-006",
    version: 1,
    reportingPeriodStart: "2026-05-15",
    reportingPeriodEnd: "2026-06-14",
    preparedBy: "Omar Farouk",
    reviewedBy: null,
    approvedBy: null,
    status: "DRAFT",
    weatherSummary: "Seasonal — hot, dry.",
    siteConditions: "Productive.",
    workCompleted: "Structure to L12; façade to L9; overall 42% complete.",
    workPlannedNextPeriod: "Structure to L18; façade watertight to L12.",
    manpowerSummary: [{ trade: "All trades (avg/day)", count: 96, hours: 9 }],
    materialDeliveries: "Monthly summary attached.",
    safetyIncidents: "1 near miss in period; 0 LTI.",
    qualityIssues: "2 NCRs raised, both closed.",
    delays: "Façade bracket lot — 1 week, recovered.",
    risks: "Procurement of lot-2 brackets; lift installation sequencing.",
    notes: "Executive summary to be finalised before issue.",
    createdAt: "2026-06-15",
    updatedAt: "2026-06-15",
  },
];

type CertSeed = Omit<
  ProgressCertification,
  "workCompletedValue" | "retentionAmount" | "amountRecommendedForPayment"
>;

function cert(seed: CertSeed): ProgressCertification {
  const calc = progressPayment({
    contractValue: seed.contractValue,
    currentPercentComplete: seed.currentPercentComplete,
    retentionPercentage: seed.retentionPercentage,
    previousPaymentsValue: seed.previousPaymentsValue,
  });
  return { ...seed, ...calc };
}

export const SEED_CERTIFICATIONS: ProgressCertification[] = [
  cert({
    id: "cert_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    certificationNumber: "PC-2026-014-006",
    version: 1,
    inspectionDate: "2026-06-14",
    certifiedBy: "Omar Farouk",
    lenderName: "First Abu Dhabi Bank",
    contractorName: "Tameer Construction",
    contractValue: 2791000,
    currency: "AED",
    previousPercentComplete: 36,
    currentPercentComplete: 42,
    retentionPercentage: 10,
    previousPaymentsValue: 904000,
    deficiencies: "Minor — honeycombing at C-7 patched; no impact on certification.",
    recommendation: "Recommended for payment as certified.",
    status: "ISSUED",
    createdAt: "2026-06-14",
    updatedAt: "2026-06-14",
  }),
  cert({
    id: "cert_002",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    certificationNumber: "PC-2026-009-004",
    version: 1,
    inspectionDate: "2026-06-13",
    certifiedBy: "Sara Khan",
    lenderName: "Abu Dhabi Commercial Bank",
    contractorName: "Trojan General Contracting",
    contractValue: 3200000,
    currency: "AED",
    previousPercentComplete: 14,
    currentPercentComplete: 19,
    retentionPercentage: 10,
    previousPaymentsValue: 403200,
    deficiencies: "None observed.",
    recommendation: "Recommended for payment.",
    status: "APPROVED",
    createdAt: "2026-06-13",
    updatedAt: "2026-06-15",
  }),
  cert({
    id: "cert_003",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    certificationNumber: "PC-2026-022-002",
    version: 1,
    inspectionDate: "2026-06-16",
    certifiedBy: "Layla Hassan",
    lenderName: "Emirates NBD",
    contractorName: "ASGC",
    contractValue: 1850000,
    currency: "AED",
    previousPercentComplete: 22,
    currentPercentComplete: 28,
    retentionPercentage: 5,
    previousPaymentsValue: 386650,
    deficiencies: "Pending podium slab snagging.",
    recommendation: "Recommended subject to snag close-out.",
    status: "DRAFT",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-17",
  }),
];

export const SEED_PUNCH_ITEMS: PunchListItem[] = [
  {
    id: "punch_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    itemNumber: "PL-2026-014-031",
    location: "Level 8 — Unit 0804, master bedroom",
    description: "Paint finish to feature wall scuffed during MEP second-fix; make good and repaint.",
    trade: "Painting",
    responsibleParty: "Tameer Construction",
    priority: "LOW",
    status: "OPEN",
    dateIdentified: "2026-06-15",
    dueDate: "2026-06-22",
    dateCompleted: null,
    verifiedBy: null,
    notes: null,
    createdAt: "2026-06-15",
    updatedAt: "2026-06-15",
  },
  {
    id: "punch_002",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    itemNumber: "PL-2026-014-032",
    location: "Level 8 — Unit 0806, ensuite",
    description: "Shower mixer leaking at wall plate; reseal and pressure-test.",
    trade: "Plumbing",
    responsibleParty: "Tameer Construction",
    priority: "HIGH",
    status: "IN_PROGRESS",
    dateIdentified: "2026-06-14",
    dueDate: "2026-06-18",
    dateCompleted: null,
    verifiedBy: null,
    notes: "Plumber on site 17 Jun; awaiting re-test.",
    createdAt: "2026-06-14",
    updatedAt: "2026-06-17",
  },
  {
    id: "punch_003",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    itemNumber: "PL-2026-009-007",
    location: "Ground floor — main gallery, gridline C",
    description: "Heritage stone cladding panel chipped at lower corner; replace panel.",
    trade: "Stone / Cladding",
    responsibleParty: "Trojan General Contracting",
    priority: "MEDIUM",
    status: "COMPLETED",
    dateIdentified: "2026-06-10",
    dueDate: "2026-06-16",
    dateCompleted: "2026-06-16",
    verifiedBy: null,
    notes: "Replacement panel installed; awaiting consultant verification.",
    createdAt: "2026-06-10",
    updatedAt: "2026-06-16",
  },
  {
    id: "punch_004",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    itemNumber: "PL-2026-009-008",
    location: "External — north entrance ramp",
    description: "Handrail end return not compliant with accessibility spec; rework to detail A-512.",
    trade: "Metalwork",
    responsibleParty: "Trojan General Contracting",
    priority: "CRITICAL",
    status: "OPEN",
    dateIdentified: "2026-06-16",
    dueDate: "2026-06-20",
    dateCompleted: null,
    verifiedBy: null,
    notes: "Safety/compliance — close before handover.",
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
  },
  {
    id: "punch_005",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    itemNumber: "PL-2026-022-014",
    location: "Podium roof — drainage outlet RWP-3",
    description: "Rainwater outlet ponding; adjust falls in screed and re-test.",
    trade: "Waterproofing",
    responsibleParty: "ASGC",
    priority: "HIGH",
    status: "VERIFIED",
    dateIdentified: "2026-06-08",
    dueDate: "2026-06-14",
    dateCompleted: "2026-06-13",
    verifiedBy: "Layla Hassan",
    notes: "Re-tested and signed off.",
    createdAt: "2026-06-08",
    updatedAt: "2026-06-14",
  },
];

export const SEED_SITE_INSTRUCTIONS: SiteInstruction[] = [
  {
    id: "si_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    instructionNumber: "SI-2026-014-018",
    title: "Relocate L3 plant room access door 600 mm east",
    description:
      "Following the revised MEP layout, relocate the plant room access door to clear the new chilled-water riser. Maintain fire rating and ironmongery spec.",
    issuedBy: "Omar Farouk",
    issuedTo: "Tameer Construction",
    discipline: "ARCHITECTURAL",
    costImpact: "POSSIBLE",
    scheduleImpact: "NONE",
    linkedChangeOrderId: "co_002",
    status: "ISSUED",
    dateIssued: "2026-06-15",
    createdAt: "2026-06-15",
    updatedAt: "2026-06-15",
  },
  {
    id: "si_002",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    instructionNumber: "SI-2026-014-019",
    title: "Apply additional rebar tie to columns C-6 / C-7",
    description: "Add intermediate ties at 150 mm c/c over the lower 1 m of columns C-6 and C-7 per engineer's mark-up.",
    issuedBy: "ZenArch Structural",
    issuedTo: "Tameer Construction",
    discipline: "STRUCTURAL",
    costImpact: "NONE",
    scheduleImpact: "NONE",
    linkedChangeOrderId: null,
    status: "ACKNOWLEDGED",
    dateIssued: "2026-06-12",
    createdAt: "2026-06-12",
    updatedAt: "2026-06-13",
  },
  {
    id: "si_003",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    instructionNumber: "SI-2026-009-005",
    title: "Heritage cladding mock-up — proceed with locally sourced stone",
    description: "Construct the gallery cladding mock-up using the locally sourced limestone substitution pending CO approval.",
    issuedBy: "Sara Khan",
    issuedTo: "Trojan General Contracting",
    discipline: "ARCHITECTURAL",
    costImpact: "CONFIRMED",
    scheduleImpact: "POSSIBLE",
    linkedChangeOrderId: "co_003",
    status: "DRAFT",
    dateIssued: null,
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
  },
];

export const SEED_SUBMITTALS: Submittal[] = [
  {
    id: "sub_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    submittalNumber: "SUB-2026-014-052",
    title: "Curtain wall shop drawings — Levels 9–12",
    description: "Fabrication shop drawings and structural calcs for the unitised curtain wall, L9–L12 setback zone.",
    submittedBy: "Tameer Construction",
    reviewedBy: "ZenArch Structural",
    discipline: "STRUCTURAL",
    status: "REVISE_AND_RESUBMIT",
    dateRequired: "2026-06-10",
    dateSubmitted: "2026-06-09",
    dateReviewed: "2026-06-13",
    reviewerComments: "Add intermediate bracket at the L9 setback per SK-114; resubmit affected sheets.",
    createdAt: "2026-06-09",
    updatedAt: "2026-06-13",
  },
  {
    id: "sub_002",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    submittalNumber: "SUB-2026-014-053",
    title: "Waterproofing system — L3 plant room",
    description: "Product data and warranty for the tanking system to the revised plant room.",
    submittedBy: "Tameer Construction",
    reviewedBy: "ZenArch MEP",
    discipline: "PLUMBING",
    status: "APPROVED_AS_NOTED",
    dateRequired: "2026-06-15",
    dateSubmitted: "2026-06-14",
    dateReviewed: "2026-06-16",
    reviewerComments: "Approved per spec 07 13 00; ensure detailing at upstands matches A-512.",
    createdAt: "2026-06-14",
    updatedAt: "2026-06-16",
  },
  {
    id: "sub_003",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    submittalNumber: "SUB-2026-009-021",
    title: "Heritage stone — material sample & test certificates",
    description: "Physical samples and compliance test certificates for the proposed locally sourced limestone.",
    submittedBy: "Trojan General Contracting",
    reviewedBy: null,
    discipline: "ARCHITECTURAL",
    status: "SUBMITTED",
    dateRequired: "2026-06-18",
    dateSubmitted: "2026-06-15",
    dateReviewed: null,
    reviewerComments: null,
    createdAt: "2026-06-15",
    updatedAt: "2026-06-15",
  },
  {
    id: "sub_004",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    submittalNumber: "SUB-2026-022-009",
    title: "Feature lighting — luminaire schedule & samples",
    description: "Luminaire schedule, photometrics and samples for the podium perimeter feature lighting.",
    submittedBy: "ASGC",
    reviewedBy: null,
    discipline: "ELECTRICAL",
    status: "REQUIRED",
    dateRequired: "2026-06-24",
    dateSubmitted: null,
    dateReviewed: null,
    reviewerComments: null,
    createdAt: "2026-06-17",
    updatedAt: "2026-06-17",
  },
];

export const SEED_DELAY_NOTICES: DelayNotice[] = [
  {
    id: "dn_001",
    projectId: "PRJ-2026-014",
    projectName: "Marina Heights Tower — Phase 2",
    delayNoticeNumber: "DN-2026-014-003",
    title: "Façade bracket lot-2 delivery delay",
    description: "Late delivery of the second curtain-wall bracket lot impacted façade installation to L11.",
    cause: "Supplier production / freight delay.",
    responsibleParty: "Tameer Construction (supplier)",
    claimedDays: 7,
    approvedDays: 5,
    costImpact: 18500,
    currency: "AED",
    status: "ACCEPTED",
    dateStarted: "2026-06-06",
    dateResolved: "2026-06-13",
    createdAt: "2026-06-07",
    updatedAt: "2026-06-14",
  },
  {
    id: "dn_002",
    projectId: "PRJ-2026-009",
    projectName: "Saadiyat Cultural Pavilion",
    delayNoticeNumber: "DN-2026-009-002",
    title: "Heritage stone import lead-time delay",
    description: "Specified imported limestone long-lead time threatens the cladding programme; substitution under review.",
    cause: "Procurement / long-lead import.",
    responsibleParty: "Owner / design",
    claimedDays: 14,
    approvedDays: 0,
    costImpact: 0,
    currency: "AED",
    status: "UNDER_REVIEW",
    dateStarted: "2026-06-10",
    dateResolved: null,
    createdAt: "2026-06-11",
    updatedAt: "2026-06-16",
  },
  {
    id: "dn_003",
    projectId: "PRJ-2026-022",
    projectName: "Creek Harbour Retail Podium",
    delayNoticeNumber: "DN-2026-022-001",
    title: "Podium roof ponding rework",
    description: "Rework to roof falls at RWP-3 delayed waterproofing sign-off and follow-on screed.",
    cause: "Workmanship — falls out of tolerance.",
    responsibleParty: "ASGC",
    claimedDays: 4,
    approvedDays: 0,
    costImpact: 0,
    currency: "AED",
    status: "SUBMITTED",
    dateStarted: "2026-06-12",
    dateResolved: null,
    createdAt: "2026-06-13",
    updatedAt: "2026-06-13",
  },
];
